pr:
 branches:
   include:
     - master
 paths:
   include:
    - docs/*

jobs:
  - job: lint
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: docker pull github/super-linter:latest
      displayName: Pull GitHub Super-Linter image
    - script: >-
        docker run \
          -e RUN_LOCAL=true \
          -e VALIDATE_MARKDOWN=true \
          -e FILTER_REGEX_INCLUDE=.*docs/.* \
          -v $(System.DefaultWorkingDirectory):/tmp/lint \
          github/super-linter
      displayName: 'Run Linter'